### ISSUE TITLE
Exporting animations

### ISSUE THREAD

**Issue by tilkinsc** [yyc12345/vtobjplugin#4]
Have you accessed the possibility to export animations and 'bones'? Asking before I waste my time trying.

**Comment by yyc12345** [comment]
0. OBJ do not support bones and animations, so this issue will not be resolved in this project.
0. I am not familiar with bones and animations, just because my work rarely involve these features.
0. *Just in my view*, Virtools does not support bones. But it supports animations.
0. Virtools provides corresponding API to access animations data, so it is possible to export animations as some universal formats such as glTF.
0. I delegated some work to my friend about 2 years ago. The detail of this work is that export some animations of a single ball, put it into Blender and render it. But that animations are too simple, just the combination of position and rotation. I am not sure whether it is possible to export some complex animations.

**Comment by tilkinsc** [comment]
Thanks for your insight
